# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{caplock}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Dru Ibarra}]
  s.date = %q{2012-01-10}
  s.description = %q{Adds a lock file to Capistrano deployments to prevent concurrent deployments.}
  s.email = %q{Druwerd@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "caplock.gemspec",
     "lib/caplock.rb",
     "test/helper.rb",
     "test/test_caplock.rb"
  ]
  s.homepage = %q{http://github.com/Druwerd/caplock}
  s.rdoc_options = [%q{--charset=UTF-8}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Adds a lock file to Capistrano deployments}
  s.test_files = [
    "test/helper.rb",
     "test/test_caplock.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 2.9.0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<capistrano>, [">= 2.9.0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 2.9.0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

